# prometheus.yml
global:
  scrape_interval: 15s # Set the scrape interval to 15 seconds

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node_exporter'
    static_configs:
    - targets: ['node_exporter:9100']

  - job_name: 'ksql'
    static_configs:
      - targets: ['ksqldb-server:7072']
    metrics_path: /metrics
