CREATE STREAM LFB (
        INCIDENTNUMBER STRING, 
        DATEOFCALL STRING, 
        CALYEAR STRING, 
        TIMEOFCALL STRING, 
        HOUROFCALL STRING, 
        INCIDENTGROUP STRING, 
        INCIDENTSTATIONGROUND STRING, 
        FIRSTPUMPARRIVING_ATTENDANCETIME STRING
        ) 
        WITH (
            KAFKA_TOPIC='incident', 
            KEY_FORMAT='KAFKA', 
            VALUE_FORMAT='AVRO'
            );

CREATE TABLE LFB_STATIONS_EVENTS 
WITH (
    KAFKA_TOPIC='LFB_STATIONS_EVENTS', 
    KEY_FORMAT='AVRO', 
    PARTITIONS=1, 
    REPLICAS=1) AS 
    SELECT 
        LFB.INCIDENTSTATIONGROUND INCIDENTSTATIONGROUND, 
        LFB.INCIDENTGROUP INCIDENTGROUP, 
        COUNT(*) TOTALEVENTS 
    FROM LFB LFB 
    GROUP BY LFB.INCIDENTSTATIONGROUND, LFB.INCIDENTGROUP 
EMIT CHANGES;

CREATE TABLE LFB_METRICS WITH (KAFKA_TOPIC='LFB_METRICS', KEY_FORMAT='AVRO', VALUE_FORMAT='AVRO', PARTITIONS=1, REPLICAS=1) AS 
    SELECT
        DATEOFCALL,   
        INCIDENTSTATIONGROUND,   
        INCIDENTGROUP,
        COUNT(*) AS TOTALEVENTS, 
        SUM(CAST(FIRSTPUMPARRIVING_ATTENDANCETIME AS INTEGER)) AS TOTAL_ATTENDANCETIME 
    FROM 
        LFB 
    GROUP BY 
        INCIDENTSTATIONGROUND, 
        INCIDENTGROUP,
        DATEOFCALL 
EMIT CHANGES;

CREATE TABLE LFB_STATIONS_EVENTS_APP 
WITH (
    KAFKA_TOPIC='LFB_STATIONS_EVENTS_APP', 
    KEY_FORMAT='AVRO', 
    PARTITIONS=1, 
    REPLICAS=1) AS 
    SELECT 
        LFB.INCIDENTSTATIONGROUND INCIDENTSTATIONGROUND, 
        LFB.INCIDENTGROUP INCIDENTGROUP, 
        COUNT(*) TOTALEVENTS 
    FROM LFB LFB 
    GROUP BY LFB.INCIDENTSTATIONGROUND, LFB.INCIDENTGROUP 
EMIT CHANGES;