CREATE STREAM PAGEVIEWS (
        USER_ID INT, 
        POSTCODE STRING, 
        WEBPAGE STRING, 
        AT_TIME TIMESTAMP
        ) 
        WITH (
            KAFKA_TOPIC='page_views', 
            KEY_FORMAT='KAFKA', 
            VALUE_FORMAT='AVRO'
            );

CREATE TABLE PAGE_VIWES_COUNT 
WITH (
    KAFKA_TOPIC='PAGE_VIWES_COUNT', 
    KEY_FORMAT='AVRO', 
    PARTITIONS=1, 
    REPLICAS=1) AS 
    SELECT 
        PV.POSTCODE POSTCODE, 
        COUNT(*) TOTAL_VIEWS
    FROM PAGEVIEWS PV 
    WINDOW TUMBLING (SIZE 1 MINUTE)
    GROUP BY PV.POSTCODE
EMIT FINAL;