{
 "title": "Nobl9 Agents",
 "description": "Nobl9 Agents dashboard",
 "tags": [
  "nobl9",
  "slo",
  "nobl9-agents"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   { "name": "agent_name", "label": "Agent name", "query": { "query": "label_values(nobl9_agent_name)" } }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "SLIs count",
   "type": "stat",
   "description": "Count of unique service level indicators ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (nobl9_agent_name, nobl9_agent_project)(n9_sli_total{nobl9_agent_name=~\"$agent_name\"})",
     "legendFormat": "{{nobl9_agent_name}}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (nobl9_agent_name) (n9_uptime{nobl9_agent_name=~\"$agent_name\"})",
     "legendFormat": "{{nobl9_agent_name}}"
    }
   ]
  },
  {
   "title": "Last successful connection to Nobl9",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (nobl9_agent_name) (rate(n9_last_config_update_success_time{nobl9_agent_name=~\"$agent_name\"}[$__rate_interval])) * 60",
     "legendFormat": "{{nobl9_agent_name}}"
    }
   ]
  },
  { "title": "Data intake  [$agent_name]", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Query latency",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le) (increase(n9_query_latency_bucket{nobl9_agent_name=~\"$agent_name\"}[$__rate_interval])))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (le) (increase(n9_query_latency_bucket{nobl9_agent_name=~\"$agent_name\"}[$__rate_interval])))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.50, sum by (le) (increase(n9_query_latency_bucket{nobl9_agent_name=~\"$agent_name\"}[$__rate_interval])))",
     "legendFormat": "p50"
    }
   ]
  },
  {
   "title": "Data source query latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le) (increase(n9_query_latency_bucket{ nobl9_agent_name=~\"$agent_name\"}[$__rate_interval])))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (le) (increase(n9_query_latency_bucket{ nobl9_agent_name=~\"$agent_name\"}[$__rate_interval])))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.50, sum by (le) (increase(n9_query_latency_bucket{  nobl9_agent_name=~\"$agent_name\"}[$__rate_interval])))",
     "legendFormat": "p50"
    }
   ]
  },
  {
   "title": "Last successful request to the data source",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (nobl9_agent_name) (n9_last_input_successful_response_time{nobl9_agent_name=~\"$agent_name\"})",
     "legendFormat": "{{nobl9_agent_name}}"
    }
   ]
  },
  {
   "title": "Requests count (per minute)",
   "type": "timeseries",
   "description": "The number of requests to the data source with HTTP status.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": "sum(rate(n9_query_total{status_code=~\"2..\", nobl9_agent_name=~\"$agent_name\"}[$__rate_interval])) by (status_code) * 60",
     "legendFormat": "HTTP {{status_code}}"
    },
    {
     "expr": "sum(rate(n9_query_total{status_code!~\"2..\", nobl9_agent_name=~\"$agent_name\"}[$__rate_interval])) by (nobl9_agent_name, status_code) * 60",
     "legendFormat": "HTTP {{status_code}}"
    }
   ]
  },
  {
   "title": "Points obtained (per minute)",
   "type": "timeseries",
   "description": "The number of metric points returned in the response.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "sum by(nobl9_agent_name) (rate(n9_accumulated_points{nobl9_agent_name=~\"$agent_name\"}[$__rate_interval])) * 60",
     "legendFormat": "{{nobl9_agent_name}}"
    }
   ]
  },
  { "title": "Data upload [$agent_name]", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "Uploaded points (per minute)",
   "type": "timeseries",
   "description": "The number of points uploaded to Nobl9.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "targets": [
    {
     "expr": "sum by(nobl9_agent_name) (rate(n9_emitted_points{nobl9_agent_name=~\"$agent_name\"}[$__rate_interval])) * 60",
     "legendFormat": "{{nobl9_agent_name}}"
    }
   ]
  },
  {
   "title": "Points uploaded to Nobl9 since launch",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (nobl9_agent_name) (n9_emitted_points{nobl9_agent_name=~\"$agent_name\"})",
     "legendFormat": "{{nobl9_agent_name}}"
    }
   ]
  },
  {
   "title": "Data upload latency [All]",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le) (increase(n9_direct_upload_latency_bucket{}[$__rate_interval])))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (le) (increase(n9_direct_upload_latency_bucket{}[$__rate_interval])))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.50, sum by (le) (increase(n9_direct_upload_latency_bucket{}[$__rate_interval])))",
     "legendFormat": "p50"
    }
   ]
  },
  {
   "title": "Data upload latency [All]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le) (increase(n9_direct_upload_latency_bucket{}[$__rate_interval])))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (le) (increase(n9_direct_upload_latency_bucket{}[$__rate_interval])))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.50, sum by (le) (increase(n9_direct_upload_latency_bucket{}[$__rate_interval])))",
     "legendFormat": "p50"
    }
   ]
  }
 ]
}